### ISSUE TITLE
CPS1: Fix Forgotten Worlds stars

### ISSUE THREAD

**Issue by jotego** [jotego/jtcps1#111]
I broke it when fixed Strider's! It should be a matter of mapping the ROM correctly.

**Comment by jotego** [comment]
Fixed in e5c3779

**Comment by paulb-nl** [comment]
I am still seeing broken stars with Forgotten Worlds ever since release jtcps1_20211002. Including 20211226 and 20220112.
